;clash的转换模板，自用，请勿引用。

[custom]
;设置github分流规则
ruleset=Apple Serve,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple.list
ruleset=Google Serve,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=OneDrive,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list
ruleset=Microsoft Serve,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
ruleset=Spotify Serve,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
ruleset=YouTube Serve,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=TikTok Serve,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=Emby Serve,https://raw.githubusercontent.com/gloooom/other/refs/heads/main/Emby.list
ruleset=Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=No Ads,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/BanAD.yaml
ruleset=No Ads,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AdvertisingMiTV/AdvertisingMiTV.list
ruleset=Dct,[]GEOIP,CN
ruleset=Last,[]FINAL
;设置github分流规则

;故障转移策略组
custom_proxy_group=Proxy`select`[]Manual`[]Auto`[]HongKong`[]Taiwan`[]Japan`[]Singapore`[]USA`[]Other`[]Boon
custom_proxy_group=Manual`select`.*
custom_proxy_group=Apple Serve`fallback`[]USA`[]Japan`[]Taiwan`[]Singapore`[]HongKong`[]Other`[]Boon`[]Proxy`[]Manual`[]DIRECT`http://cp.cloudflare.com/generate_204`300
custom_proxy_group=Google Serve`fallback`[]USA`[]Japan`[]Taiwan`[]Singapore`[]HongKong`[]Other`[]Boon`[]Proxy`[]Manual`[]DIRECT`http://cp.cloudflare.com/generate_204`300
custom_proxy_group=OneDrive`select`[]HongKong`[]Taiwan`[]Japan`[]Singapore`[]USA`[]Other`[]Boon`[]Proxy`[]Manual`[]DIRECT
custom_proxy_group=Microsoft Serve`fallback`[]USA`[]Japan`[]Taiwan`[]Singapore`[]HongKong`[]Other`[]Boon`[]Proxy`[]Manual`[]DIRECT`http://cp.cloudflare.com/generate_204`300
custom_proxy_group=Spotify Serve`fallback`[]HongKong`[]Taiwan`[]Japan`[]Singapore`[]USA`[]Other`[]Boon`[]Proxy`[]Manual`[]DIRECT`http://cp.cloudflare.com/generate_204`300
custom_proxy_group=YouTube Serve`fallback`[]USA`[]Japan`[]Taiwan`[]Singapore`[]HongKong`[]Other`[]Boon`[]Proxy`[]Manual`[]DIRECT`http://cp.cloudflare.com/generate_204`300
custom_proxy_group=TikTok Serve`fallback`[]Japan`[]Taiwan`[]Singapore`[]USA`[]HongKong`[]Other`[]Boon`[]Proxy`[]Manual`[]DIRECT`http://cp.cloudflare.com/generate_204`300
custom_proxy_group=Emby Serve`fallback`[]Boon`[]HongKong`[]Taiwan`[]Japan`[]Singapore`[]USA`[]Other`[]Proxy`[]Manual`[]DIRECT`http://cp.cloudflare.com/generate_204`300
custom_proxy_group=Telegram`fallback`[]Boon`[]HongKong`[]Taiwan`[]Japan`[]Singapore`[]USA`[]Other`[]Proxy`[]Manual`[]DIRECT`http://cp.cloudflare.com/generate_204`300
custom_proxy_group=No Ads`select`[]REJECT`[]DIRECT
custom_proxy_group=Dct`select`[]DIRECT`[]Proxy`[]Manual
custom_proxy_group=Last`fallback`[]USA`[]Japan`[]Taiwan`[]Singapore`[]HongKong`[]Other`[]Boon`[]Proxy`[]Manual`[]DIRECT`http://cp.cloudflare.com/generate_204`300

;自动测速组服务于上方故障转移策略组
custom_proxy_group=Auto`url-test`^((?!(1.5|1.2|1.8|2.0|2.5|3.0|5.0)).)*$`http://cp.cloudflare.com/generate_204`300,3,200
custom_proxy_group=HongKong`url-test`(?=.*(🇭🇰|港|(?i)Hong|(?i)HK))^((?!(劫持|专用)).)*$`http://cp.cloudflare.com/generate_204`300,3,200
custom_proxy_group=Taiwan`url-test`(?=.*(🇨🇳|台|(?i)Tai|(?i)TW))^((?!(劫持|专用)).)*$`http://cp.cloudflare.com/generate_204`300,3,200
custom_proxy_group=Japan`url-test`(?=.*(🇯🇵|日|(?i)Japan|(?i)JP))^((?!(劫持|专用|尼日)).)*$`http://cp.cloudflare.com/generate_204`300,3,200
custom_proxy_group=Singapore`url-test`(?=.*(🇸🇬|新|(?i)Singapore|(?i)SG))^((?!(劫持|专用)).)*$`http://cp.cloudflare.com/generate_204`300,3,200
custom_proxy_group=USA`url-test`(?=.*(🇺🇸|美|(?i)States|(?i)US))^((?!(劫持|专用)).)*$`http://cp.cloudflare.com/generate_204`300,3,200
custom_proxy_group=Other`url-test`^((?!(🇭🇰|港|(?i)Hong|(?i)HK|🇨🇳|台|(?i)Tai|(?i)TW|🇯🇵|日|(?i)Japan|(?i)JP|🇸🇬|新|(?i)Singapore|(?i)SG|🇺🇸|美|(?i)States|(?i)US)).)*$`http://cp.cloudflare.com/generate_204`300,3,200
custom_proxy_group=Boon`url-test`(?=.*(0.0|0.01|0.1|0.2|0.20x|0.3|0.5|福利))^((?!(劫持|专用)).)*$`http://cp.cloudflare.com/generate_204`300,3,200


enable_rule_generator=true
overwrite_original_rules=true
